update trap version
drosera-network/examples pull request #14
Opened 2024-07-25 15:55 UTC by An0nJon

2024-07-26 14:06 UTC, scglenn commented
Lets hold off on merging until we have the functionality merged into the main dro repo and have dev docs updated

2024-07-26 14:06 UTC, scglenn requested changes

2024-07-26 14:34 UTC, An0nJon commented on bridges/nomad/packages/interfaces/ITrap.sol
> +    function isValid(bytes[] calldata data) external view returns (bool, bytes memory);
For the isValid params?

2024-07-28 04:39 UTC, scglenn requested changes

2024-07-28 04:39 UTC, scglenn commented on bridges/nomad/packages/interfaces/ITrap.sol
> +    function isValid(bytes[] calldata data) external view returns (bool, bytes memory);
isValid should be pure for ITrap.sol instead of view

2024-07-29 13:52 UTC, scglenn approved these changes

2024-07-29 21:33 UTC, merged