proactive TWAP trap example
drosera-network/examples pull request #6
Opened 2024-05-06 14:32 UTC by An0nJon

Trap example to demonstrate a proactive detection of a multi-block oracle manipulation using time-series data.

2024-05-06 16:02 UTC, scglenn commented on oracles/twap/src/TWAPTrap.sol
> +import {Test, console2} from "forge-std/Test.sol";
This isnt needed in the Trap.sol right?

2024-05-06 16:13 UTC, scglenn requested changes

2024-05-06 16:13 UTC, scglenn commented on oracles/twap/src/TWAPTrap.sol
> +        return PriceDataPoint({price: 0});
I would prefer to query a mockOracle so we avoid confusion with some of the early examples of traps

2024-05-06 16:32 UTC, An0nJon commented on oracles/twap/src/TWAPTrap.sol
> +        if (dataPointsLength < 2 || dataPointsLength < dataPointsToCheck) {
I see. Ill rip that part out.

2024-05-07 11:09 UTC, scglenn requested changes

2024-05-07 11:09 UTC, scglenn commented on oracles/twap/README.md
> +- It provides a `collect` function that is not used to retrieve mock oracle data.
the collect function is used instead of a mock now, remove this line

2024-05-07 13:24 UTC, scglenn approved these changes

2024-05-08 13:59 UTC, merged