Added some examples from the dorahacks workshop
drosera-network/examples pull request #7
Opened 2024-06-20 16:02 UTC by scglenn

2024-06-20 16:09 UTC, An0nJon requested changes

2024-06-20 16:09 UTC, An0nJon commented on bridges/nomad/test/nomad.t.sol
> +        // users = ScenarioUtils.createUsers(10);
do these comments need to be here?

2024-06-20 16:09 UTC, An0nJon commented on bridges/nomad/README.md
> +
Do we need a small read me here?

2024-07-01 21:20 UTC, scglenn commented on bridges/nomad/test/nomad.t.sol
> +        // users = ScenarioUtils.createUsers(10);
removed

2024-07-01 21:22 UTC, scglenn commented on bridges/nomad/README.md
> +
Adding

2024-07-01 21:44 UTC, An0nJon approved these changes

2024-07-01 21:48 UTC, merged